spring.cloud.openfeign.client.config.product.url=http://localhost:8080
spring.datasource.url=jdbc:postgresql://localhost:5433/cart-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db.changelog/db.changelog-master.yaml
server.port=8081
spring.main.allow-circular-references=true